"""empty message

Revision ID: 2e9085036a4d
Revises: None
Create Date: 2021-04-23 23:23:25.648276

"""

# revision identifiers, used by Alembic.
revision = '2e9085036a4d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('label', sa.Unicode(), nullable=True),
    sa.Column('summary', sa.Unicode(), nullable=True),
    sa.Column('foreign_id', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('foreign_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection')
    # ### end Alembic commands ###
