"""empty message

Revision ID: 3640ab086153
Revises: bafb6c637f1b
Create Date: 2021-05-21 22:42:53.185423

"""

# revision identifiers, used by Alembic.
revision = '3640ab086153'
down_revision = 'bafb6c637f1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('foreign_id', sa.Unicode(), nullable=True))
    op.create_index(op.f('ix_document_foreign_id'), 'document', ['foreign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_foreign_id'), table_name='document')
    op.drop_column('document', 'foreign_id')
    # ### end Alembic commands ###
