"""empty message

Revision ID: 79b4676deb40
Revises: e5325f05f210
Create Date: 2021-04-24 04:20:02.653757

"""

# revision identifiers, used by Alembic.
revision = '79b4676deb40'
down_revision = 'e5325f05f210'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
