"""empty message

Revision ID: c27264411515
Revises: 8d2852258e20
Create Date: 2021-05-15 22:36:02.396224

"""

# revision identifiers, used by Alembic.
revision = 'c27264411515'
down_revision = '8d2852258e20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_entity_collection_id'), 'entity', ['collection_id'], unique=False)
    op.create_foreign_key(None, 'entity', 'collection', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entity', type_='foreignkey')
    op.drop_index(op.f('ix_entity_collection_id'), table_name='entity')
    op.drop_column('entity', 'collection_id')
    # ### end Alembic commands ###
