"""empty message

Revision ID: e5325f05f210
Revises: d7bfc09293c9
Create Date: 2021-04-24 04:02:16.909427

"""

# revision identifiers, used by Alembic.
revision = 'e5325f05f210'
down_revision = 'd7bfc09293c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_collection_id'), 'document', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_collection_id'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
